[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_mf = "DEbamqaZ68gXpBMDwaFBDQ4TM7giTt3rJZ387FmZnsCM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
